<?php


/**
 * This class adds structure of 'sf_ezc_worflow_execution_state' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Nov 21 13:18:38 2008
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfEzcWorkflowPropelPlugin.lib.model.map
 */
class sfEzcWorkflowExecutionStateMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfEzcWorkflowPropelPlugin.lib.model.map.sfEzcWorkflowExecutionStateMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(sfEzcWorkflowExecutionStatePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(sfEzcWorkflowExecutionStatePeer::TABLE_NAME);
		$tMap->setPhpName('sfEzcWorkflowExecutionState');
		$tMap->setClassname('sfEzcWorkflowExecutionState');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('EXECUTION_ID', 'ExecutionId', 'INTEGER' , 'sf_ezc_worflow_execution', 'ID', true, null);

		$tMap->addForeignPrimaryKey('NODE_ID', 'NodeId', 'INTEGER' , 'sf_ezc_worflow_node', 'ID', true, null);

		$tMap->addColumn('STATE', 'State', 'LONGVARCHAR', true, null);

		$tMap->addColumn('ACTIVATED_FROM', 'ActivatedFrom', 'LONGVARCHAR', true, null);

		$tMap->addColumn('THREAD_ID', 'ThreadId', 'INTEGER', true, null);

	} // doBuild()

} // sfEzcWorkflowExecutionStateMapBuilder
