<?php


/**
 * This class adds structure of 'sf_ezc_worflow_node' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Nov 21 13:18:38 2008
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfEzcWorkflowPropelPlugin.lib.model.map
 */
class sfEzcWorkflowNodeMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfEzcWorkflowPropelPlugin.lib.model.map.sfEzcWorkflowNodeMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(sfEzcWorkflowNodePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(sfEzcWorkflowNodePeer::TABLE_NAME);
		$tMap->setPhpName('sfEzcWorkflowNode');
		$tMap->setClassname('sfEzcWorkflowNode');

		$tMap->setUseIdGenerator(true);

		$tMap->addForeignKey('WORKFLOW_ID', 'WorkflowId', 'INTEGER', 'sf_ezc_worflow', 'ID', true, null);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('CLASSNAME', 'Classname', 'VARCHAR', true, 255);

		$tMap->addColumn('CONFIGURATION', 'Configuration', 'LONGVARCHAR', true, null);

	} // doBuild()

} // sfEzcWorkflowNodeMapBuilder
