<?php

/**
 * Base class that represents a row from the 'sf_ezc_worflow_node' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Nov 21 13:18:38 2008
 *
 * @package    plugins.sfEzcWorkflowPropelPlugin.lib.model.om
 */
abstract class BasesfEzcWorkflowNode extends BaseObject  implements Persistent {


  const PEER = 'sfEzcWorkflowNodePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        sfEzcWorkflowNodePeer
	 */
	protected static $peer;

	/**
	 * The value for the workflow_id field.
	 * @var        int
	 */
	protected $workflow_id;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the classname field.
	 * @var        string
	 */
	protected $classname;

	/**
	 * The value for the configuration field.
	 * @var        string
	 */
	protected $configuration;

	/**
	 * @var        sfEzcWorkflow
	 */
	protected $asfEzcWorkflow;

	/**
	 * @var        array sfEzcWorkflowExecutionState[] Collection to store aggregation of sfEzcWorkflowExecutionState objects.
	 */
	protected $collsfEzcWorkflowExecutionStates;

	/**
	 * @var        Criteria The criteria used to select the current contents of collsfEzcWorkflowExecutionStates.
	 */
	private $lastsfEzcWorkflowExecutionStateCriteria = null;

	/**
	 * @var        array sfEzcWorkflowNodeConnection[] Collection to store aggregation of sfEzcWorkflowNodeConnection objects.
	 */
	protected $collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId.
	 */
	private $lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria = null;

	/**
	 * @var        array sfEzcWorkflowNodeConnection[] Collection to store aggregation of sfEzcWorkflowNodeConnection objects.
	 */
	protected $collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId.
	 */
	private $lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasesfEzcWorkflowNode object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [workflow_id] column value.
	 * 
	 * @return     int
	 */
	public function getWorkflowId()
	{
		return $this->workflow_id;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [classname] column value.
	 * 
	 * @return     string
	 */
	public function getClassname()
	{
		return $this->classname;
	}

	/**
	 * Get the [configuration] column value.
	 * 
	 * @return     string
	 */
	public function getConfiguration()
	{
		return $this->configuration;
	}

	/**
	 * Set the value of [workflow_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfEzcWorkflowNode The current object (for fluent API support)
	 */
	public function setWorkflowId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->workflow_id !== $v) {
			$this->workflow_id = $v;
			$this->modifiedColumns[] = sfEzcWorkflowNodePeer::WORKFLOW_ID;
		}

		if ($this->asfEzcWorkflow !== null && $this->asfEzcWorkflow->getId() !== $v) {
			$this->asfEzcWorkflow = null;
		}

		return $this;
	} // setWorkflowId()

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfEzcWorkflowNode The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = sfEzcWorkflowNodePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [classname] column.
	 * 
	 * @param      string $v new value
	 * @return     sfEzcWorkflowNode The current object (for fluent API support)
	 */
	public function setClassname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->classname !== $v) {
			$this->classname = $v;
			$this->modifiedColumns[] = sfEzcWorkflowNodePeer::CLASSNAME;
		}

		return $this;
	} // setClassname()

	/**
	 * Set the value of [configuration] column.
	 * 
	 * @param      string $v new value
	 * @return     sfEzcWorkflowNode The current object (for fluent API support)
	 */
	public function setConfiguration($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->configuration !== $v) {
			$this->configuration = $v;
			$this->modifiedColumns[] = sfEzcWorkflowNodePeer::CONFIGURATION;
		}

		return $this;
	} // setConfiguration()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->workflow_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->classname = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->configuration = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = sfEzcWorkflowNodePeer::NUM_COLUMNS - sfEzcWorkflowNodePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating sfEzcWorkflowNode object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfEzcWorkflow !== null && $this->workflow_id !== $this->asfEzcWorkflow->getId()) {
			$this->asfEzcWorkflow = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfEzcWorkflowNodePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = sfEzcWorkflowNodePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfEzcWorkflow = null;
			$this->collsfEzcWorkflowExecutionStates = null;
			$this->lastsfEzcWorkflowExecutionStateCriteria = null;

			$this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId = null;
			$this->lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria = null;

			$this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId = null;
			$this->lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfEzcWorkflowNode:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfEzcWorkflowNodePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			sfEzcWorkflowNodePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasesfEzcWorkflowNode:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfEzcWorkflowNode:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfEzcWorkflowNodePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasesfEzcWorkflowNode:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			sfEzcWorkflowNodePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfEzcWorkflow !== null) {
				if ($this->asfEzcWorkflow->isModified() || $this->asfEzcWorkflow->isNew()) {
					$affectedRows += $this->asfEzcWorkflow->save($con);
				}
				$this->setsfEzcWorkflow($this->asfEzcWorkflow);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = sfEzcWorkflowNodePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = sfEzcWorkflowNodePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += sfEzcWorkflowNodePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collsfEzcWorkflowExecutionStates !== null) {
				foreach ($this->collsfEzcWorkflowExecutionStates as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId !== null) {
				foreach ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId !== null) {
				foreach ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfEzcWorkflow !== null) {
				if (!$this->asfEzcWorkflow->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfEzcWorkflow->getValidationFailures());
				}
			}


			if (($retval = sfEzcWorkflowNodePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collsfEzcWorkflowExecutionStates !== null) {
					foreach ($this->collsfEzcWorkflowExecutionStates as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId !== null) {
					foreach ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId !== null) {
					foreach ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfEzcWorkflowNodePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getWorkflowId();
				break;
			case 1:
				return $this->getId();
				break;
			case 2:
				return $this->getClassname();
				break;
			case 3:
				return $this->getConfiguration();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = sfEzcWorkflowNodePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getWorkflowId(),
			$keys[1] => $this->getId(),
			$keys[2] => $this->getClassname(),
			$keys[3] => $this->getConfiguration(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfEzcWorkflowNodePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setWorkflowId($value);
				break;
			case 1:
				$this->setId($value);
				break;
			case 2:
				$this->setClassname($value);
				break;
			case 3:
				$this->setConfiguration($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = sfEzcWorkflowNodePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setWorkflowId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setClassname($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setConfiguration($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);

		if ($this->isColumnModified(sfEzcWorkflowNodePeer::WORKFLOW_ID)) $criteria->add(sfEzcWorkflowNodePeer::WORKFLOW_ID, $this->workflow_id);
		if ($this->isColumnModified(sfEzcWorkflowNodePeer::ID)) $criteria->add(sfEzcWorkflowNodePeer::ID, $this->id);
		if ($this->isColumnModified(sfEzcWorkflowNodePeer::CLASSNAME)) $criteria->add(sfEzcWorkflowNodePeer::CLASSNAME, $this->classname);
		if ($this->isColumnModified(sfEzcWorkflowNodePeer::CONFIGURATION)) $criteria->add(sfEzcWorkflowNodePeer::CONFIGURATION, $this->configuration);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);

		$criteria->add(sfEzcWorkflowNodePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of sfEzcWorkflowNode (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setWorkflowId($this->workflow_id);

		$copyObj->setClassname($this->classname);

		$copyObj->setConfiguration($this->configuration);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getsfEzcWorkflowExecutionStates() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfEzcWorkflowExecutionState($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfEzcWorkflowNodeConnectionRelatedByIncomingNodeId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeId($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     sfEzcWorkflowNode Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     sfEzcWorkflowNodePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new sfEzcWorkflowNodePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfEzcWorkflow object.
	 *
	 * @param      sfEzcWorkflow $v
	 * @return     sfEzcWorkflowNode The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfEzcWorkflow(sfEzcWorkflow $v = null)
	{
		if ($v === null) {
			$this->setWorkflowId(NULL);
		} else {
			$this->setWorkflowId($v->getId());
		}

		$this->asfEzcWorkflow = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfEzcWorkflow object, it will not be re-added.
		if ($v !== null) {
			$v->addsfEzcWorkflowNode($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfEzcWorkflow object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfEzcWorkflow The associated sfEzcWorkflow object.
	 * @throws     PropelException
	 */
	public function getsfEzcWorkflow(PropelPDO $con = null)
	{
		if ($this->asfEzcWorkflow === null && ($this->workflow_id !== null)) {
			$c = new Criteria(sfEzcWorkflowPeer::DATABASE_NAME);
			$c->add(sfEzcWorkflowPeer::ID, $this->workflow_id);
			$this->asfEzcWorkflow = sfEzcWorkflowPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfEzcWorkflow->addsfEzcWorkflowNodes($this);
			 */
		}
		return $this->asfEzcWorkflow;
	}

	/**
	 * Clears out the collsfEzcWorkflowExecutionStates collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfEzcWorkflowExecutionStates()
	 */
	public function clearsfEzcWorkflowExecutionStates()
	{
		$this->collsfEzcWorkflowExecutionStates = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfEzcWorkflowExecutionStates collection (array).
	 *
	 * By default this just sets the collsfEzcWorkflowExecutionStates collection to an empty array (like clearcollsfEzcWorkflowExecutionStates());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfEzcWorkflowExecutionStates()
	{
		$this->collsfEzcWorkflowExecutionStates = array();
	}

	/**
	 * Gets an array of sfEzcWorkflowExecutionState objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this sfEzcWorkflowNode has previously been saved, it will retrieve
	 * related sfEzcWorkflowExecutionStates from storage. If this sfEzcWorkflowNode is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array sfEzcWorkflowExecutionState[]
	 * @throws     PropelException
	 */
	public function getsfEzcWorkflowExecutionStates($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfEzcWorkflowExecutionStates === null) {
			if ($this->isNew()) {
			   $this->collsfEzcWorkflowExecutionStates = array();
			} else {

				$criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->id);

				sfEzcWorkflowExecutionStatePeer::addSelectColumns($criteria);
				$this->collsfEzcWorkflowExecutionStates = sfEzcWorkflowExecutionStatePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->id);

				sfEzcWorkflowExecutionStatePeer::addSelectColumns($criteria);
				if (!isset($this->lastsfEzcWorkflowExecutionStateCriteria) || !$this->lastsfEzcWorkflowExecutionStateCriteria->equals($criteria)) {
					$this->collsfEzcWorkflowExecutionStates = sfEzcWorkflowExecutionStatePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastsfEzcWorkflowExecutionStateCriteria = $criteria;
		return $this->collsfEzcWorkflowExecutionStates;
	}

	/**
	 * Returns the number of related sfEzcWorkflowExecutionState objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfEzcWorkflowExecutionState objects.
	 * @throws     PropelException
	 */
	public function countsfEzcWorkflowExecutionStates(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collsfEzcWorkflowExecutionStates === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->id);

				$count = sfEzcWorkflowExecutionStatePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->id);

				if (!isset($this->lastsfEzcWorkflowExecutionStateCriteria) || !$this->lastsfEzcWorkflowExecutionStateCriteria->equals($criteria)) {
					$count = sfEzcWorkflowExecutionStatePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collsfEzcWorkflowExecutionStates);
				}
			} else {
				$count = count($this->collsfEzcWorkflowExecutionStates);
			}
		}
		$this->lastsfEzcWorkflowExecutionStateCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a sfEzcWorkflowExecutionState object to this object
	 * through the sfEzcWorkflowExecutionState foreign key attribute.
	 *
	 * @param      sfEzcWorkflowExecutionState $l sfEzcWorkflowExecutionState
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfEzcWorkflowExecutionState(sfEzcWorkflowExecutionState $l)
	{
		if ($this->collsfEzcWorkflowExecutionStates === null) {
			$this->initsfEzcWorkflowExecutionStates();
		}
		if (!in_array($l, $this->collsfEzcWorkflowExecutionStates, true)) { // only add it if the **same** object is not already associated
			array_push($this->collsfEzcWorkflowExecutionStates, $l);
			$l->setsfEzcWorkflowNode($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this sfEzcWorkflowNode is new, it will return
	 * an empty collection; or if this sfEzcWorkflowNode has previously
	 * been saved, it will retrieve related sfEzcWorkflowExecutionStates from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in sfEzcWorkflowNode.
	 */
	public function getsfEzcWorkflowExecutionStatesJoinsfEzcWorkflowExecution($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfEzcWorkflowExecutionStates === null) {
			if ($this->isNew()) {
				$this->collsfEzcWorkflowExecutionStates = array();
			} else {

				$criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->id);

				$this->collsfEzcWorkflowExecutionStates = sfEzcWorkflowExecutionStatePeer::doSelectJoinsfEzcWorkflowExecution($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->id);

			if (!isset($this->lastsfEzcWorkflowExecutionStateCriteria) || !$this->lastsfEzcWorkflowExecutionStateCriteria->equals($criteria)) {
				$this->collsfEzcWorkflowExecutionStates = sfEzcWorkflowExecutionStatePeer::doSelectJoinsfEzcWorkflowExecution($criteria, $con, $join_behavior);
			}
		}
		$this->lastsfEzcWorkflowExecutionStateCriteria = $criteria;

		return $this->collsfEzcWorkflowExecutionStates;
	}

	/**
	 * Clears out the collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId()
	 */
	public function clearsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId()
	{
		$this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId collection (array).
	 *
	 * By default this just sets the collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId collection to an empty array (like clearcollsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId()
	{
		$this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId = array();
	}

	/**
	 * Gets an array of sfEzcWorkflowNodeConnection objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this sfEzcWorkflowNode has previously been saved, it will retrieve
	 * related sfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId from storage. If this sfEzcWorkflowNode is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array sfEzcWorkflowNodeConnection[]
	 * @throws     PropelException
	 */
	public function getsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId === null) {
			if ($this->isNew()) {
			   $this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId = array();
			} else {

				$criteria->add(sfEzcWorkflowNodeConnectionPeer::INCOMING_NODE_ID, $this->id);

				sfEzcWorkflowNodeConnectionPeer::addSelectColumns($criteria);
				$this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId = sfEzcWorkflowNodeConnectionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(sfEzcWorkflowNodeConnectionPeer::INCOMING_NODE_ID, $this->id);

				sfEzcWorkflowNodeConnectionPeer::addSelectColumns($criteria);
				if (!isset($this->lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria) || !$this->lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria->equals($criteria)) {
					$this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId = sfEzcWorkflowNodeConnectionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria = $criteria;
		return $this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId;
	}

	/**
	 * Returns the number of related sfEzcWorkflowNodeConnection objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfEzcWorkflowNodeConnection objects.
	 * @throws     PropelException
	 */
	public function countsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(sfEzcWorkflowNodeConnectionPeer::INCOMING_NODE_ID, $this->id);

				$count = sfEzcWorkflowNodeConnectionPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(sfEzcWorkflowNodeConnectionPeer::INCOMING_NODE_ID, $this->id);

				if (!isset($this->lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria) || !$this->lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria->equals($criteria)) {
					$count = sfEzcWorkflowNodeConnectionPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId);
				}
			} else {
				$count = count($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId);
			}
		}
		$this->lastsfEzcWorkflowNodeConnectionRelatedByIncomingNodeIdCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a sfEzcWorkflowNodeConnection object to this object
	 * through the sfEzcWorkflowNodeConnection foreign key attribute.
	 *
	 * @param      sfEzcWorkflowNodeConnection $l sfEzcWorkflowNodeConnection
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfEzcWorkflowNodeConnectionRelatedByIncomingNodeId(sfEzcWorkflowNodeConnection $l)
	{
		if ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId === null) {
			$this->initsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId();
		}
		if (!in_array($l, $this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId, $l);
			$l->setsfEzcWorkflowNodeRelatedByIncomingNodeId($this);
		}
	}

	/**
	 * Clears out the collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId()
	 */
	public function clearsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId()
	{
		$this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId collection (array).
	 *
	 * By default this just sets the collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId collection to an empty array (like clearcollsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId()
	{
		$this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId = array();
	}

	/**
	 * Gets an array of sfEzcWorkflowNodeConnection objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this sfEzcWorkflowNode has previously been saved, it will retrieve
	 * related sfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId from storage. If this sfEzcWorkflowNode is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array sfEzcWorkflowNodeConnection[]
	 * @throws     PropelException
	 */
	public function getsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId === null) {
			if ($this->isNew()) {
			   $this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId = array();
			} else {

				$criteria->add(sfEzcWorkflowNodeConnectionPeer::OUTGOING_NODE_ID, $this->id);

				sfEzcWorkflowNodeConnectionPeer::addSelectColumns($criteria);
				$this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId = sfEzcWorkflowNodeConnectionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(sfEzcWorkflowNodeConnectionPeer::OUTGOING_NODE_ID, $this->id);

				sfEzcWorkflowNodeConnectionPeer::addSelectColumns($criteria);
				if (!isset($this->lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria) || !$this->lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria->equals($criteria)) {
					$this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId = sfEzcWorkflowNodeConnectionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria = $criteria;
		return $this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId;
	}

	/**
	 * Returns the number of related sfEzcWorkflowNodeConnection objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfEzcWorkflowNodeConnection objects.
	 * @throws     PropelException
	 */
	public function countsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(sfEzcWorkflowNodeConnectionPeer::OUTGOING_NODE_ID, $this->id);

				$count = sfEzcWorkflowNodeConnectionPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(sfEzcWorkflowNodeConnectionPeer::OUTGOING_NODE_ID, $this->id);

				if (!isset($this->lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria) || !$this->lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria->equals($criteria)) {
					$count = sfEzcWorkflowNodeConnectionPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId);
				}
			} else {
				$count = count($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId);
			}
		}
		$this->lastsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeIdCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a sfEzcWorkflowNodeConnection object to this object
	 * through the sfEzcWorkflowNodeConnection foreign key attribute.
	 *
	 * @param      sfEzcWorkflowNodeConnection $l sfEzcWorkflowNodeConnection
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfEzcWorkflowNodeConnectionRelatedByOutgoingNodeId(sfEzcWorkflowNodeConnection $l)
	{
		if ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId === null) {
			$this->initsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId();
		}
		if (!in_array($l, $this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId, $l);
			$l->setsfEzcWorkflowNodeRelatedByOutgoingNodeId($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collsfEzcWorkflowExecutionStates) {
				foreach ((array) $this->collsfEzcWorkflowExecutionStates as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId) {
				foreach ((array) $this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId) {
				foreach ((array) $this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collsfEzcWorkflowExecutionStates = null;
		$this->collsfEzcWorkflowNodeConnectionsRelatedByIncomingNodeId = null;
		$this->collsfEzcWorkflowNodeConnectionsRelatedByOutgoingNodeId = null;
			$this->asfEzcWorkflow = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasesfEzcWorkflowNode:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasesfEzcWorkflowNode::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasesfEzcWorkflowNode
