<?php

/**
 * Base class that represents a row from the 'sf_ezc_worflow_execution_state' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Nov 21 13:18:38 2008
 *
 * @package    plugins.sfEzcWorkflowPropelPlugin.lib.model.om
 */
abstract class BasesfEzcWorkflowExecutionState extends BaseObject  implements Persistent {


  const PEER = 'sfEzcWorkflowExecutionStatePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        sfEzcWorkflowExecutionStatePeer
	 */
	protected static $peer;

	/**
	 * The value for the execution_id field.
	 * @var        int
	 */
	protected $execution_id;

	/**
	 * The value for the node_id field.
	 * @var        int
	 */
	protected $node_id;

	/**
	 * The value for the state field.
	 * @var        string
	 */
	protected $state;

	/**
	 * The value for the activated_from field.
	 * @var        string
	 */
	protected $activated_from;

	/**
	 * The value for the thread_id field.
	 * @var        int
	 */
	protected $thread_id;

	/**
	 * @var        sfEzcWorkflowExecution
	 */
	protected $asfEzcWorkflowExecution;

	/**
	 * @var        sfEzcWorkflowNode
	 */
	protected $asfEzcWorkflowNode;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasesfEzcWorkflowExecutionState object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [execution_id] column value.
	 * 
	 * @return     int
	 */
	public function getExecutionId()
	{
		return $this->execution_id;
	}

	/**
	 * Get the [node_id] column value.
	 * 
	 * @return     int
	 */
	public function getNodeId()
	{
		return $this->node_id;
	}

	/**
	 * Get the [state] column value.
	 * 
	 * @return     string
	 */
	public function getState()
	{
		return $this->state;
	}

	/**
	 * Get the [activated_from] column value.
	 * 
	 * @return     string
	 */
	public function getActivatedFrom()
	{
		return $this->activated_from;
	}

	/**
	 * Get the [thread_id] column value.
	 * 
	 * @return     int
	 */
	public function getThreadId()
	{
		return $this->thread_id;
	}

	/**
	 * Set the value of [execution_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfEzcWorkflowExecutionState The current object (for fluent API support)
	 */
	public function setExecutionId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->execution_id !== $v) {
			$this->execution_id = $v;
			$this->modifiedColumns[] = sfEzcWorkflowExecutionStatePeer::EXECUTION_ID;
		}

		if ($this->asfEzcWorkflowExecution !== null && $this->asfEzcWorkflowExecution->getId() !== $v) {
			$this->asfEzcWorkflowExecution = null;
		}

		return $this;
	} // setExecutionId()

	/**
	 * Set the value of [node_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfEzcWorkflowExecutionState The current object (for fluent API support)
	 */
	public function setNodeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->node_id !== $v) {
			$this->node_id = $v;
			$this->modifiedColumns[] = sfEzcWorkflowExecutionStatePeer::NODE_ID;
		}

		if ($this->asfEzcWorkflowNode !== null && $this->asfEzcWorkflowNode->getId() !== $v) {
			$this->asfEzcWorkflowNode = null;
		}

		return $this;
	} // setNodeId()

	/**
	 * Set the value of [state] column.
	 * 
	 * @param      string $v new value
	 * @return     sfEzcWorkflowExecutionState The current object (for fluent API support)
	 */
	public function setState($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->state !== $v) {
			$this->state = $v;
			$this->modifiedColumns[] = sfEzcWorkflowExecutionStatePeer::STATE;
		}

		return $this;
	} // setState()

	/**
	 * Set the value of [activated_from] column.
	 * 
	 * @param      string $v new value
	 * @return     sfEzcWorkflowExecutionState The current object (for fluent API support)
	 */
	public function setActivatedFrom($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->activated_from !== $v) {
			$this->activated_from = $v;
			$this->modifiedColumns[] = sfEzcWorkflowExecutionStatePeer::ACTIVATED_FROM;
		}

		return $this;
	} // setActivatedFrom()

	/**
	 * Set the value of [thread_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfEzcWorkflowExecutionState The current object (for fluent API support)
	 */
	public function setThreadId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->thread_id !== $v) {
			$this->thread_id = $v;
			$this->modifiedColumns[] = sfEzcWorkflowExecutionStatePeer::THREAD_ID;
		}

		return $this;
	} // setThreadId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->execution_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->node_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->state = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->activated_from = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->thread_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = sfEzcWorkflowExecutionStatePeer::NUM_COLUMNS - sfEzcWorkflowExecutionStatePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating sfEzcWorkflowExecutionState object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfEzcWorkflowExecution !== null && $this->execution_id !== $this->asfEzcWorkflowExecution->getId()) {
			$this->asfEzcWorkflowExecution = null;
		}
		if ($this->asfEzcWorkflowNode !== null && $this->node_id !== $this->asfEzcWorkflowNode->getId()) {
			$this->asfEzcWorkflowNode = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfEzcWorkflowExecutionStatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = sfEzcWorkflowExecutionStatePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfEzcWorkflowExecution = null;
			$this->asfEzcWorkflowNode = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfEzcWorkflowExecutionState:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfEzcWorkflowExecutionStatePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			sfEzcWorkflowExecutionStatePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasesfEzcWorkflowExecutionState:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfEzcWorkflowExecutionState:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfEzcWorkflowExecutionStatePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasesfEzcWorkflowExecutionState:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			sfEzcWorkflowExecutionStatePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfEzcWorkflowExecution !== null) {
				if ($this->asfEzcWorkflowExecution->isModified() || $this->asfEzcWorkflowExecution->isNew()) {
					$affectedRows += $this->asfEzcWorkflowExecution->save($con);
				}
				$this->setsfEzcWorkflowExecution($this->asfEzcWorkflowExecution);
			}

			if ($this->asfEzcWorkflowNode !== null) {
				if ($this->asfEzcWorkflowNode->isModified() || $this->asfEzcWorkflowNode->isNew()) {
					$affectedRows += $this->asfEzcWorkflowNode->save($con);
				}
				$this->setsfEzcWorkflowNode($this->asfEzcWorkflowNode);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = sfEzcWorkflowExecutionStatePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += sfEzcWorkflowExecutionStatePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfEzcWorkflowExecution !== null) {
				if (!$this->asfEzcWorkflowExecution->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfEzcWorkflowExecution->getValidationFailures());
				}
			}

			if ($this->asfEzcWorkflowNode !== null) {
				if (!$this->asfEzcWorkflowNode->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfEzcWorkflowNode->getValidationFailures());
				}
			}


			if (($retval = sfEzcWorkflowExecutionStatePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfEzcWorkflowExecutionStatePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getExecutionId();
				break;
			case 1:
				return $this->getNodeId();
				break;
			case 2:
				return $this->getState();
				break;
			case 3:
				return $this->getActivatedFrom();
				break;
			case 4:
				return $this->getThreadId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = sfEzcWorkflowExecutionStatePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getExecutionId(),
			$keys[1] => $this->getNodeId(),
			$keys[2] => $this->getState(),
			$keys[3] => $this->getActivatedFrom(),
			$keys[4] => $this->getThreadId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfEzcWorkflowExecutionStatePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setExecutionId($value);
				break;
			case 1:
				$this->setNodeId($value);
				break;
			case 2:
				$this->setState($value);
				break;
			case 3:
				$this->setActivatedFrom($value);
				break;
			case 4:
				$this->setThreadId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = sfEzcWorkflowExecutionStatePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setExecutionId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNodeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setState($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setActivatedFrom($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setThreadId($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(sfEzcWorkflowExecutionStatePeer::DATABASE_NAME);

		if ($this->isColumnModified(sfEzcWorkflowExecutionStatePeer::EXECUTION_ID)) $criteria->add(sfEzcWorkflowExecutionStatePeer::EXECUTION_ID, $this->execution_id);
		if ($this->isColumnModified(sfEzcWorkflowExecutionStatePeer::NODE_ID)) $criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->node_id);
		if ($this->isColumnModified(sfEzcWorkflowExecutionStatePeer::STATE)) $criteria->add(sfEzcWorkflowExecutionStatePeer::STATE, $this->state);
		if ($this->isColumnModified(sfEzcWorkflowExecutionStatePeer::ACTIVATED_FROM)) $criteria->add(sfEzcWorkflowExecutionStatePeer::ACTIVATED_FROM, $this->activated_from);
		if ($this->isColumnModified(sfEzcWorkflowExecutionStatePeer::THREAD_ID)) $criteria->add(sfEzcWorkflowExecutionStatePeer::THREAD_ID, $this->thread_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(sfEzcWorkflowExecutionStatePeer::DATABASE_NAME);

		$criteria->add(sfEzcWorkflowExecutionStatePeer::EXECUTION_ID, $this->execution_id);
		$criteria->add(sfEzcWorkflowExecutionStatePeer::NODE_ID, $this->node_id);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getExecutionId();

		$pks[1] = $this->getNodeId();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setExecutionId($keys[0]);

		$this->setNodeId($keys[1]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of sfEzcWorkflowExecutionState (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setExecutionId($this->execution_id);

		$copyObj->setNodeId($this->node_id);

		$copyObj->setState($this->state);

		$copyObj->setActivatedFrom($this->activated_from);

		$copyObj->setThreadId($this->thread_id);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     sfEzcWorkflowExecutionState Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     sfEzcWorkflowExecutionStatePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new sfEzcWorkflowExecutionStatePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfEzcWorkflowExecution object.
	 *
	 * @param      sfEzcWorkflowExecution $v
	 * @return     sfEzcWorkflowExecutionState The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfEzcWorkflowExecution(sfEzcWorkflowExecution $v = null)
	{
		if ($v === null) {
			$this->setExecutionId(NULL);
		} else {
			$this->setExecutionId($v->getId());
		}

		$this->asfEzcWorkflowExecution = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfEzcWorkflowExecution object, it will not be re-added.
		if ($v !== null) {
			$v->addsfEzcWorkflowExecutionState($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfEzcWorkflowExecution object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfEzcWorkflowExecution The associated sfEzcWorkflowExecution object.
	 * @throws     PropelException
	 */
	public function getsfEzcWorkflowExecution(PropelPDO $con = null)
	{
		if ($this->asfEzcWorkflowExecution === null && ($this->execution_id !== null)) {
			$c = new Criteria(sfEzcWorkflowExecutionPeer::DATABASE_NAME);
			$c->add(sfEzcWorkflowExecutionPeer::ID, $this->execution_id);
			$this->asfEzcWorkflowExecution = sfEzcWorkflowExecutionPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfEzcWorkflowExecution->addsfEzcWorkflowExecutionStates($this);
			 */
		}
		return $this->asfEzcWorkflowExecution;
	}

	/**
	 * Declares an association between this object and a sfEzcWorkflowNode object.
	 *
	 * @param      sfEzcWorkflowNode $v
	 * @return     sfEzcWorkflowExecutionState The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfEzcWorkflowNode(sfEzcWorkflowNode $v = null)
	{
		if ($v === null) {
			$this->setNodeId(NULL);
		} else {
			$this->setNodeId($v->getId());
		}

		$this->asfEzcWorkflowNode = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfEzcWorkflowNode object, it will not be re-added.
		if ($v !== null) {
			$v->addsfEzcWorkflowExecutionState($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfEzcWorkflowNode object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfEzcWorkflowNode The associated sfEzcWorkflowNode object.
	 * @throws     PropelException
	 */
	public function getsfEzcWorkflowNode(PropelPDO $con = null)
	{
		if ($this->asfEzcWorkflowNode === null && ($this->node_id !== null)) {
			$c = new Criteria(sfEzcWorkflowNodePeer::DATABASE_NAME);
			$c->add(sfEzcWorkflowNodePeer::ID, $this->node_id);
			$this->asfEzcWorkflowNode = sfEzcWorkflowNodePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfEzcWorkflowNode->addsfEzcWorkflowExecutionStates($this);
			 */
		}
		return $this->asfEzcWorkflowNode;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->asfEzcWorkflowExecution = null;
			$this->asfEzcWorkflowNode = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasesfEzcWorkflowExecutionState:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasesfEzcWorkflowExecutionState::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasesfEzcWorkflowExecutionState
